#!/bin/sh
heroku config:set ALGOLIA_APP_ID=CBRX9GBWPS
heroku config:set ALGOLIA_SECRET=bc2131413036bc5d9dcec38335daf6ff

heroku config:set APP_URL=fritzmuller.herokuapp.com

heroku config:set GOOGLE_RECAPTCHA_KEY=6LdgDBYTAAAAAN6RpxiDWiK8GML7LaUdNZHrQLWS
heroku config:set GOOGLE_RECAPTCHA_SECRET=6LdgDBYTAAAAAPqtLzPREOyDsjQAeR9ABE_rOkqf

heroku config:set JWT_SECRET=cg4IFk1STdOf1XhsrprcHDSzsvQHrpj0
